USE sakila; 

-- 1.List the number of films per category.

SELECT * FROM film_category;

SELECT * FROM film;

SELECT f.film_id, f.title, fc.category_id FROM sakila.film AS f
JOIN sakila.film_category AS fc
ON f.film_id = fc.film_id;

-- 2. Retrieve the store ID, city, and country for each store.
SELECT s.store_id, ci.city, co.country FROM sakila.store AS s
JOIN sakila.address AS a 
ON s.address_id = a.address_id
JOIN sakila.city AS ci 
ON a.city_id = ci.city_id
JOIN sakila.country AS co 
ON ci.country_id = co.country_id;

-- 3. Calculate the total revenue generated by each store in dollars.
SELECT * FROM payment;

SELECT * FROM store;

SELECT s.store_id, SUM(p.amount) AS total_revenue FROM sakila.payment AS p
JOIN sakila.rental AS r 
ON p.rental_id = r.rental_id
JOIN sakila.inventory AS i 
ON r.inventory_id = i.inventory_id
JOIN sakila.store AS s 
ON i.store_id = s.store_id
GROUP BY s.store_id;

-- 4. Determine the average running time of films for each category

SELECT AVG(f.length)AS average_running_time, c.name AS category_name FROM sakila.film AS f
JOIN sakila.film_category AS fc
ON f.film_id = fc.film_id
JOIN sakila.category AS c 
ON fc.category_id= c.category_id
GROUP BY c.name;